# Generated by Django 2.1.15 on 2020-10-26 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV_NUMBER', models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True)),
                ('CANDIDATE_CODE', models.CharField(blank=True, max_length=100, null=True)),
                ('FIRST_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('LAST_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('DATE_OF_BIRTH', models.CharField(blank=True, max_length=100, null=True)),
                ('GENDER', models.CharField(blank=True, choices=[('', '---------'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=50, null=True)),
                ('PAN_NUMBER', models.CharField(blank=True, max_length=10, null=True)),
                ('MOBILE_NUMBER', models.CharField(blank=True, max_length=10, null=True)),
                ('ALTERNATE_PHONE', models.CharField(blank=True, max_length=30, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=150, null=True)),
                ('SECONDARY_EMAIL', models.EmailField(blank=True, max_length=150, null=True)),
                ('QUALIFICATION', models.CharField(blank=True, max_length=255, null=True)),
                ('WORK_EXPERIENCE', models.CharField(blank=True, max_length=100, null=True)),
                ('CURRENT_LOCATION', models.CharField(blank=True, max_length=100, null=True)),
                ('SKILLS', models.TextField(blank=True, null=True)),
                ('SOURCE', models.CharField(blank=True, max_length=100, null=True)),
                ('SUB_SOURCE', models.CharField(blank=True, max_length=100, null=True)),
                ('DESIGNATION', models.CharField(blank=True, max_length=100, null=True)),
                ('DEPARTMENT', models.CharField(blank=True, max_length=100, null=True)),
                ('GRADE', models.CharField(blank=True, max_length=100, null=True)),
                ('PO_NUMBER', models.CharField(blank=True, max_length=100, null=True)),
                ('REMARKS', models.CharField(blank=True, max_length=1000, null=True)),
                ('CANDIDATE_OWNER', models.CharField(blank=True, max_length=100, null=True)),
                ('RESUME', models.FileField(blank=True, null=True, upload_to='CV_Repository/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])])),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
