# Generated by Django 3.0.10 on 2021-01-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_auto_20210104_2243'),
        ('client', '0002_auto_20201029_2104'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtracker',
            name='CANDIDATE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Candidate'),
        ),
        migrations.AlterField(
            model_name='billingtracker',
            name='CUSTOMER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client'),
        ),
    ]
