# Generated by Django 3.0.10 on 2021-01-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210109_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtracker',
            name='INVOICE_NUMBER',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
