# Generated by Django 3.0.10 on 2021-01-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210109_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingtracker',
            name='CUSTOMER',
        ),
    ]
