# Generated by Django 2.1.15 on 2020-10-26 17:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import apps.recruitment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CANDIDATE_ID', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('DATE_OF_BIRTH', models.DateField(blank=True, null=True)),
                ('GENDER', models.CharField(blank=True, choices=[('', '---------'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=50, null=True)),
                ('PAN_NUMBER', models.CharField(blank=True, max_length=10, null=True)),
                ('SOURCE', models.CharField(blank=True, max_length=255, null=True)),
                ('SUB_SOURCE', models.CharField(blank=True, max_length=255, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=100, null=True)),
                ('SECONDARY_EMAIL', models.EmailField(blank=True, max_length=100, null=True)),
                ('MOBILE_NUMBER', models.CharField(blank=True, max_length=10, null=True)),
                ('ALTERNATE_PHONE', models.CharField(blank=True, max_length=30, null=True)),
                ('QUALIFICATION', models.CharField(blank=True, max_length=255, null=True)),
                ('WORK_EXPERIENCE', models.CharField(blank=True, max_length=100, null=True)),
                ('LOCATION', models.CharField(blank=True, max_length=255, null=True)),
                ('RECRUITER_CODE', models.CharField(blank=True, max_length=10, null=True)),
                ('CANDIDATE_STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('CANDIDATE_STATUS_REMARKS', models.CharField(blank=True, max_length=100, null=True)),
                ('EXPECTED_DOJ', models.DateField(blank=True, null=True)),
                ('FINAL_DOJ', models.DateField(blank=True, null=True)),
                ('DROP_OUT_REASON', models.CharField(blank=True, max_length=255, null=True)),
                ('CV_APPROVE_DATE', models.DateField(blank=True, null=True)),
                ('CV_APPROVE_BY', models.CharField(blank=True, max_length=10, null=True)),
                ('CV_REJECT_BY', models.CharField(blank=True, max_length=10, null=True)),
                ('SKILL_SET', models.CharField(blank=True, max_length=255, null=True)),
                ('RESUME', models.FileField(blank=True, null=True, upload_to=apps.recruitment.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])])),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('CREATED_BY', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, null=True)),
                ('INTERVIEW_SCHEDULED', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INTERVIEW_ID', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('INTERVIEW_TYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('INTERVIEW_ROUND', models.CharField(blank=True, max_length=100, null=True)),
                ('INTERVIEW_LOCATION', models.CharField(blank=True, max_length=255, null=True)),
                ('INTERVIEW_DATE', models.DateField(blank=True, null=True)),
                ('INTERVIEW_TIME', models.TimeField(blank=True, null=True)),
                ('INTERVIEW_STATUS', models.CharField(blank=True, max_length=100, null=True)),
                ('INTERVIEW_COMMENTS', models.CharField(blank=True, max_length=255, null=True)),
                ('REMARKS', models.CharField(blank=True, max_length=255, null=True)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('CREATED_BY', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(blank=True, editable=False, null=True)),
                ('CANDIDATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.Candidate')),
                ('INTERVIEWER_NAME', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.ClientSPOC')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JOB_CODE', models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True)),
                ('JOB_TITLE', models.CharField(blank=True, max_length=255, null=True)),
                ('NUMBER_OF_POSITIONS', models.PositiveIntegerField(blank=True, null=True)),
                ('JOB_START_DATE', models.DateField(blank=True, null=True)),
                ('TARGET_DATE', models.DateField(blank=True, null=True)),
                ('LINE_OF_BUSINESS', models.CharField(blank=True, choices=[('', '---------'), ('INTERNATIONAL', 'INTERNATIONAL'), ('DOMESTIC', 'DOMESTIC')], max_length=255, null=True)),
                ('JOB_TYPE', models.CharField(blank=True, choices=[('', '---------'), ('FULL TIME', 'FULL TIME'), ('PART TIME', 'PART TIME'), ('PERMANENT', 'PERMANENT'), ('TEMPORARY', 'TEMPORARY'), ('CONTRACT', 'CONTRACT'), ('FREELANCE', 'FREELANCE'), ('TRAINING', 'TRAINING')], max_length=255, null=True)),
                ('PRIORITY_TYPE', models.CharField(blank=True, choices=[('', '---------'), ('HIGH', 'HIGH'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM')], max_length=255, null=True)),
                ('WORK_EXPERIENCE', models.CharField(blank=True, max_length=255, null=True)),
                ('JOB_LOCATION', models.CharField(blank=True, max_length=255, null=True)),
                ('JOB_OPENING_STATUS', models.CharField(blank=True, max_length=255, null=True)),
                ('JOB_DESCRIPTION', models.TextField(blank=True, null=True)),
                ('REQUIRED_SKILLS', models.TextField(blank=True, null=True)),
                ('REQUIRED_QUALIFICATION', models.CharField(blank=True, max_length=255, null=True)),
                ('SKILL', models.CharField(blank=True, choices=[('', '---------'), ('LATERAL', 'LATERAL'), ('BPO', 'BPO')], max_length=255, null=True)),
                ('SUB_SKILL', models.CharField(blank=True, max_length=255, null=True)),
                ('JOB_SHIFT', models.CharField(blank=True, choices=[('', '---------'), ('US', 'US'), ('UK', 'UK'), ('AUS', 'AUS'), ('DAY', 'DAY'), ('24x7', '24x7')], max_length=255, null=True)),
                ('NUMBER_OF_POSITIONS_CLOSED', models.CharField(blank=True, max_length=255, null=True)),
                ('NUMBER_OF_CURRENT_POSITIONS', models.CharField(blank=True, max_length=255, null=True)),
                ('NUMBER_OF_PROFILES_SHARED', models.CharField(blank=True, max_length=255, null=True)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('CREATED_BY', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ASSIGNED_SPOC', models.ManyToManyField(to='employee.Employee')),
                ('CLIENT_CODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='JOB_CODE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Job'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='RECRUITER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
