# Generated by Django 3.0.10 on 2020-10-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='SKILL',
            field=models.CharField(blank=True, choices=[('', '---------'), ('LATERAL', 'LATERAL'), ('BPO', 'BPO'), ('BPO & LATERAL', 'BPO & LATERAL')], max_length=255, null=True),
        ),
    ]
