# Generated by Django 3.0.10 on 2021-01-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20201029_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='LAST_MODIFIED',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='LAST_MODIFIED',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='LAST_MODIFIED',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
