# Generated by Django 3.0.10 on 2021-01-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidate_billing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='BILLING_STATUS',
            field=models.CharField(blank=True, default='NOT APPLICABLE', max_length=255, null=True),
        ),
    ]
