# Generated by Django 2.1.15 on 2020-10-26 17:03

import apps.client.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUSTOMER_CODE', models.CharField(editable=False, max_length=5, unique=True)),
                ('CUSTOMER_NAME', models.CharField(max_length=255)),
                ('CUSTOMER_START_DATE', models.DateField(blank=True, null=True)),
                ('CONTRACT_START_DATE', models.DateField(blank=True, null=True)),
                ('CONTRACT_END_DATE', models.DateField(blank=True, null=True)),
                ('CORPORATE_ADDRESS', models.CharField(blank=True, max_length=255, null=True)),
                ('CORPORATE_CITY', models.CharField(blank=True, max_length=255, null=True)),
                ('CORPORATE_STATE', models.CharField(blank=True, max_length=255, null=True)),
                ('CORPORATE_PINCODE', models.CharField(blank=True, max_length=6, null=True)),
                ('CORPORATE_COUNTRY', models.CharField(blank=True, max_length=255, null=True)),
                ('BOTH_ADDRESS_SAME', models.CharField(blank=True, max_length=20, null=True)),
                ('BILLING_ADDRESS', models.CharField(blank=True, max_length=255, null=True)),
                ('BILLING_CITY', models.CharField(blank=True, max_length=255, null=True)),
                ('BILLING_STATE', models.CharField(blank=True, max_length=255, null=True)),
                ('BILLING_PINCODE', models.CharField(blank=True, max_length=6, null=True)),
                ('BILLING_COUNTRY', models.CharField(blank=True, max_length=255, null=True)),
                ('MSMED_NUMBER', models.CharField(blank=True, max_length=255, null=True)),
                ('POTENTIAL_CUSTOMER', models.CharField(blank=True, choices=[('', '---------'), ('YES', 'YES'), ('NO', 'NO')], max_length=255, null=True)),
                ('SKILL', models.CharField(blank=True, choices=[('', '---------'), ('LATERAL', 'LATERAL'), ('BPO', 'BPO')], max_length=255, null=True)),
                ('LOCATION_SERVE', models.CharField(blank=True, max_length=255, null=True)),
                ('GSTIN_NUMBER', models.CharField(blank=True, max_length=15, null=True)),
                ('PAN_NUMBER', models.CharField(blank=True, max_length=10, null=True)),
                ('REGISTERED_ON', models.DateTimeField(auto_now_add=True, null=True)),
                ('REGISTERED_BY', models.CharField(blank=True, max_length=10, null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=10, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOCUMENT_TITLE', models.CharField(max_length=100)),
                ('DOCUMENTS', models.FileField(upload_to=apps.client.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'xls', 'xlsx', 'pdf', 'zip', 'jpg', 'jpeg', 'png', 'ppt', 'pptx'])])),
                ('UPLOAD_TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('UPLOADED_BY', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('CUSTOMER_CODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSPOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOCATION', models.CharField(blank=True, max_length=255, null=True)),
                ('PERSON_NAME', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(blank=True, max_length=150, null=True)),
                ('CONTACT', models.CharField(blank=True, max_length=30, null=True)),
                ('TYPE', models.CharField(blank=True, choices=[('', '---------'), ('HR', 'HR'), ('TR', 'TR'), ('MR', 'MR'), ('OPERATIONS', 'OPERATIONS'), ('UNIT HEAD', 'UNIT HEAD'), ('BILLING', 'BILLING'), ('RECRUITMENT', 'RECRUITMENT'), ('SENIOR SPOC', 'SENIOR SPOC'), ('V&A', 'V&A'), ('APTITUDE-TEST', 'APTITUDE-TEST'), ('TEAM LEADER', 'TEAM LEADER'), ('AMCAT', 'AMCAT'), ('CHAT', 'CHAT'), ('CD CHAT', 'CD CHAT'), ('CD VOICE', 'CD VOICE'), ('VERSANT TEST', 'VERSANT TEST')], max_length=255, null=True)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('CUSTOMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
    ]
