# Generated by Django 2.1.15 on 2020-10-26 17:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import apps.employee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPLOYEE_CODE', models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True)),
                ('EMPLOYEE_FULL_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('MIDDLE_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('LAST_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('FATHER_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('DATE_OF_BIRTH', models.DateField(blank=True, null=True)),
                ('PRESENT_ADDRESS', models.CharField(blank=True, max_length=255, null=True)),
                ('PRESENT_CITY', models.CharField(blank=True, max_length=255, null=True)),
                ('PRESENT_PIN', models.CharField(blank=True, max_length=6, null=True)),
                ('GENDER', models.CharField(blank=True, choices=[('', '---------'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=255, null=True)),
                ('AGE', models.PositiveIntegerField(default=0)),
                ('EMERGENCY_CONTACT_NUMBER', models.CharField(blank=True, max_length=30, null=True)),
                ('EMERGENCY_CONTACT_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('BLOOD_GROUP', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('PRIMARY_MOBILE_NO', models.CharField(blank=True, max_length=10, null=True)),
                ('SECONDARY_MOBILE_NO', models.CharField(blank=True, max_length=10, null=True)),
                ('MARITAL_STATUS', models.CharField(blank=True, choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED'), ('DIVORCE', 'DIVORCE')], max_length=50, null=True)),
                ('PERSONNEL_EMAIL', models.EmailField(blank=True, max_length=255, null=True)),
                ('QUALIFICATION', models.CharField(blank=True, max_length=255, null=True)),
                ('NATIONALITY', models.CharField(blank=True, choices=[('', '---------'), ('INDIAN', 'INDIAN')], max_length=100, null=True)),
                ('DATE_OF_JOINING', models.DateField(blank=True, null=True)),
                ('DEPARTMENT', models.CharField(blank=True, max_length=255, null=True)),
                ('DESIGNATION', models.CharField(blank=True, max_length=255, null=True)),
                ('GRADE', models.CharField(blank=True, max_length=20, null=True)),
                ('OPS_ROLE', models.CharField(blank=True, max_length=255, null=True)),
                ('CATEGORY', models.CharField(blank=True, choices=[('', '---------'), ('LATERAL', 'LATERAL'), ('BPO', 'BPO')], max_length=255, null=True)),
                ('BRANCH', models.CharField(blank=True, max_length=255, null=True)),
                ('LOCATION', models.CharField(blank=True, max_length=255, null=True)),
                ('STATE', models.CharField(blank=True, max_length=255, null=True)),
                ('EMPLOYEE_TYPE', models.CharField(blank=True, choices=[('', '---------'), ('EXPERIENCED', 'EXPERIENCED'), ('FRESHER', 'FRESHER')], max_length=50, null=True)),
                ('EMPLOYMENT_TYPE', models.CharField(blank=True, max_length=50, null=True)),
                ('REPORTING_MANAGER_CODE', models.CharField(blank=True, max_length=7, null=True)),
                ('REPORTING_MANAGER_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('HR_MANAGER_CODE', models.CharField(blank=True, max_length=7, null=True)),
                ('HR_MANAGER_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('REFERENCE_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('REFERENCE_CONTACT_NO', models.CharField(blank=True, max_length=255, null=True)),
                ('REFERENCE_DESIGNATION', models.CharField(blank=True, max_length=255, null=True)),
                ('OFFICIAL_EMAIL', models.EmailField(blank=True, max_length=255, null=True)),
                ('DATE_OF_RESIGNATION', models.DateField(blank=True, null=True)),
                ('RELIEVING_DATE', models.DateField(blank=True, null=True)),
                ('DATE_OF_CONFIRMATION', models.DateField(blank=True, null=True)),
                ('SWIPE_ATTENDANCE_NUMBER', models.CharField(blank=True, max_length=20, null=True)),
                ('EMPLOYEE_STATUS', models.CharField(blank=True, choices=[('', '---------'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=50, null=True)),
                ('SOURCE_OF_HIRE', models.CharField(blank=True, max_length=255, null=True)),
                ('SUB_SOURCE', models.CharField(blank=True, max_length=255, null=True)),
                ('TOTAL_EXPERIENCE', models.FloatField(blank=True, null=True)),
                ('LAST_EMPLOYER_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('LAST_EMPLOYER_START_DATE', models.DateField(blank=True, null=True)),
                ('LAST_EMPLOYER_END_DATE', models.DateField(blank=True, null=True)),
                ('LAST_EMPLOYER_CTC', models.FloatField(blank=True, default=0, null=True)),
                ('AADHAAR_CARD_NO', models.CharField(blank=True, max_length=12, null=True)),
                ('BANK_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('IFSC_CODE', models.CharField(blank=True, max_length=11, null=True)),
                ('BANK_BRANCH_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('BANK_ACCOUNT_NO', models.CharField(blank=True, max_length=20, null=True)),
                ('PAN_CARD_NUMBER', models.CharField(blank=True, max_length=10, null=True)),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=10, null=True)),
                ('MODIFIED_BY', models.CharField(blank=True, max_length=10, null=True)),
                ('LAST_MODIFIED', models.DateTimeField(blank=True, editable=False, null=True)),
                ('IS_USER_CREATED', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOCUMENT_TITLE', models.CharField(max_length=100)),
                ('DOCUMENTS', models.FileField(upload_to=apps.employee.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'xls', 'xlsx', 'pdf', 'zip', 'jpg', 'jpeg', 'png', 'ppt', 'pptx'])])),
                ('UPLOAD_TIMESTAMP', models.DateTimeField(auto_now_add=True, null=True)),
                ('UPLOADED_BY', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('EMPLOYEE_CODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
